### ISSUE TITLE
Fr: disable in reading mode

### ISSUE THREAD

**Issue by eleanorkonik** [joethei/obsidian-link-favicon#19]
As much as I love this plugin, copying the favicons when I write the roundup and paste it into ghost results in really janky images being pulled over too and it messes up the formatting. Is there any way to add a setting to disable this for reading mode for a "clean preview" for copy and pasting? I only really use reading mode to export content 😂

**Comment by NomarCub** [comment]
I don't know how it affects your export, but seems to me this can be done just in a CSS snippet:

```css
.markdown-reading-view .link-favicon{
  display: none !important;
}
```
