### ISSUE TITLE
Feature Request: Disable Color Inversion Option

### ISSUE THREAD

**Issue by rmateu** [joethei/obsidian-link-favicon#28]
Understand how this could be useful to many, but for some reason most of my icons fall just on the threshold and it inverts incorrectly. 

Could an option be added to disable Color Inversion?

Thanks for the plugin!

**Comment by joethei** [comment]
This cannot be influenced by the plugin code as easily, a better solution would be if you add the  the following [css snippet](https://help.obsidian.md/How+to/Add+custom+styles#Use+Themes+and+or+CSS+snippets):
```css
.link-favicon[data-is-readable-a-a="false"] {
	filter: unset;
}

```
