### ISSUE TITLE
Bug: css Filter conflict

### ISSUE THREAD

**Issue by chrisgrieser** [joethei/obsidian-link-favicon#32]
[This line](https://github.com/joethei/obsidian-link-favicon/blob/master/src/styles.scss#L20)

```css
.link-favicon[data-is-readable-a-a="false"] {
	filter: hue-rotate(180deg) invert(1.0);
}
```

Conflicts with the [recommendation you give for grayscale icons in the README](https://github.com/joethei/obsidian-link-favicon#for-designers)

```css
.link-favicon {
	filter: grayscale(100%);
}
```
