### ISSUE TITLE
Bug: on 1.8, the icon positioning is off is broken

### ISSUE THREAD

**Issue by chrisgrieser** [joethei/obsidian-link-favicon#82]
![Pasted image 2024-12-26 at 12 17 37@2x](https://github.com/user-attachments/assets/2c0f1002-00d9-4ff3-b2a1-09749d87e266)

I used this CSS to somewhat fix the positioning, though I assume it's probably better to set this correctly in the plugin code.
```css
body .link-favicon {
	height: 1em !important;
	margin-top: 0.3em;
	margin-bottom: 0;
}
```
